<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.0">
    <title>Links for odoo-addon-sale-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-sale-exception</h1>
    <a href="https://files.pythonhosted.org/packages/77/4a/23fa8e45119e3d1c8e44ee578d0ae0c29675b780a5efca033458a51ce039/odoo_addon_sale_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=6b4313ca1abf3f211d7aa5209b2979950faa7b808e94ffe1d8d223a9c18a373b" data-requires-python="&gt;=3.8" >odoo_addon_sale_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 15170604-->