<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.0">
    <title>Links for odoo-addon-account-move-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-account-move-exception</h1>
    <a href="https://files.pythonhosted.org/packages/12/d3/e41c54fc2dbd892ddd3dd670e11b42033a16d29948084f03c56917d460f9/odoo_addon_account_move_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=48132d35ccff4d8cb48af8a59a95641c28a052c0a28ca1807b66365ee98d2b92" data-requires-python="&gt;=3.8" >odoo_addon_account_move_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 14664288-->