<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.0">
    <title>Links for pyerrors</title>
  </head>
  <body>
    <h1>Links for pyerrors</h1>
    <a href="https://files.pythonhosted.org/packages/d8/b5/06b7494659426ecfdeaae16323d20b323dd8a29054df9b7cb07b6f1b1ebe/pyerrors-2.0.0-py3-none-any.whl#sha256=2742e2f940f0aecdccc64a156e151bd01c020d59ef2564a379962232cabf31b4" data-requires-python="&gt;=3.6.0" >pyerrors-2.0.0-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/e2/1c/e2eef13bc931429eaea4683d77781177772cdb901db9a8b21f5c403b3076/pyerrors-2.0.0.tar.gz#sha256=ae5842931f53f332f39e23ce1f33155c0709d442a1912eb3ef6611aae75a5f58" data-requires-python="&gt;=3.6.0" >pyerrors-2.0.0.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/4a/68/f742742807beec2d34124132c1f55387f7d92e9a00f1583897511f0439f7/pyerrors-2.1.0-py3-none-any.whl#sha256=6f8c8f5922656800a3cea9651e5e44e385cd31326ec0d61b6ffea8d056464df3" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.0-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/b2/20/1ad7f4f9792245a90a8f2580bede9666b9d68eee6c8a949b751c8260b715/pyerrors-2.1.0.tar.gz#sha256=629652a3407cb0a81c4b349d06bc914d2ca345ca92a3d87a049268b2135a8530" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.0.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/29/a9/03faa2f7406a2262fac3ab01eeac41a152646db98f1db8071086fb140d8e/pyerrors-2.1.1-py3-none-any.whl#sha256=2068052d4a8edffce3f5c2a3bb9af6902600f02bf51f90f9a2e9506b53fce73d" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.1-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/97/31/c996f50d301cffdefe544b9ab2d3b1d5457d90e7c8baff73faa311bfcf8a/pyerrors-2.1.1.tar.gz#sha256=3515981a7a1c603d37e17475ec541ef8b171f8ce5f47dc8e0f5c27116dff8cc7" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.1.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/a9/35/8a380c3548b89d3245fa1cde2937fb08f36a3f38ad7b2c25d054856f84b6/pyerrors-2.1.2-py3-none-any.whl#sha256=148b3864fd1474067772cde035e73f5f4608203481d751c8dfdbc9ed7854c592" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/a4/0c/adc1c07d476277843ea1981fda3819b150a76f2e25c76dbc214db93b8fe2/pyerrors-2.1.2.tar.gz#sha256=6a63b5fc56d61a8a334a3917a61a4ad2a2e7aaa6aa6e0b6c410ea175a81b0285" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.2.tar.gz</a><br />
    <a href="https://files.pythonhosted.org/packages/df/5c/2241af23e17cab7cd75c475793531bfc0cc22ef2f75f2a964ead08b57567/pyerrors-2.1.3-py3-none-any.whl#sha256=aaa7b80998961ea8b3c78afdaa4f5316cc236434952e0a367dc42caa0f1f84d1" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.3-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/23/13/14f15b24e3c508aca396dd5c093579c154324353c0eedfa353c291acdcac/pyerrors-2.1.3.tar.gz#sha256=22ee92f7a4e64b8841e743568a26218d0cf2c9a75dbb5c30e07442477c87b8bc" data-requires-python="&gt;=3.6.0" >pyerrors-2.1.3.tar.gz</a><br />
    </body>
</html>
<!--SERIAL 14115000-->